name: Build Pages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17' #

      - name: (V3) Update latest meta file
        uses: ./
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: (V4) Update latest meta file
        run: |
          java -jar ./ModFileLoader/ModFileLoader-1.0-SNAPSHOT-all.jar ${{ secrets.CUSTOM_GITHUB_TOKEN_V4 }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}