name: Build Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Generate MCSR Ranked Modpacks
        run: |
          java -jar ./ModFileLoader/ModFileLoader-1.0-SNAPSHOT-all.jar

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
